### PR TITLE
Add missing enum groups

### PR DESCRIPTION
**Pull request by Perksey**
Issue: #109 
Work Tracker: Perksey#1
This is the first PR regarding this issue. Subsequent PRs will follow.

### CODE REVIEW

**Comment by Perksey** [comment]
@frederikja163 We've got some empty enum groups at the bottom.

**Comment by oddhack** [comment]
Will this receive further commits, or is it ready to merge now? Looks fine.

**Comment by Perksey** [comment]
Ready for merge now, if we make further changes we'll just open another PR but I think that's it for now :P

**Comment by pdaniell-nv** [comment]
@oddhack if you are happy with this it's approved to merge.

**Pull request merged**
