### PR TITLE
Documentation fixes for EXT_external_objects

### PR DESCRIPTION
**Pull request by lostgoat**

### CODE REVIEW

**Comment by lostgoat** [comment]
@cubanismo can you confirm whether the intended prototype for GetUnsignedByte* should include the EXT suffix or not.

**Comment by oddhack** [comment]
@cubanismo I actually meant to assign this to James Jones but he doesn't seem to have a KhronosGroup membership - can you ping him on this? Sorry for the confusion.

**Comment by lostgoat** [comment]
@oddhack if it makes things easier I can also send the pull request on gitlab. Let me know.

**Comment by cubanismo** [comment]
@oddhack That's strange.  My profile says I'm a member of KhronosGroup.

Regardless, the changes look good to me, and yes the EXT suffix should be there.  That's how it's listed in the headers/XML, and that's how it's exported in our driver.

**Comment by oddhack** [comment]
@cubanismo it must be some other permissions thing then - your name does not come up in the 'Assignees' dropdown menu / selection widget.

**Comment by oddhack** [comment]
@cubanismo @jeffbolznv accepting this, but I noticed the EXT_external_objects* extensions aren't in gl.xml and aren't getting added to the generated header. I'll fix that eventually but feel free to get to it first if you care about that.

**Comment by cubanismo** [comment]
@oddhack The extensions are in the XML and show up in the public header.  Note their names are GL_EXT_semaphore* and GL_EXT_memory_object*, not GL_EXT_external_objects*.  The latter is just the filename for their shared spec document.

**Pull request merged**
