### PR TITLE
Add EXT_texture_storage_compression and EXT_EGL_image_storage_compression

### PR DESCRIPTION
**Pull request by janharaldfredriksen-arm**

### CODE REVIEW

**Comment by janharaldfredriksen-arm** [comment]
CC: @pdaniell-nv, @oddhack

**Comment by pdaniell-nv** [comment]
Approved to merge based on previous WG discussions. @janharaldfredriksen-arm you may want to remove the generated files, but maybe if there are no conflicts @oddhack will just merge anyway.

**Comment by oddhack** [comment]
LGTM, merging.

**Comment by stonesthrow** [comment]
👍

**Comment by NogginBops** [comment]
Just curious as to why these functions take arguments of type `const int *attrib_list` instead of `const GLint *attrib_list`?
This might not be the place to ask, if so I would like to be redirected to where I can ask this question. 🙂

**Pull request merged**
