### PR TITLE
add QCOM_texture_foveated2

### PR DESCRIPTION
**Pull request by jackohound**
Adds vendor extension QCOM_texture_foveated2.

### CODE REVIEW

**Comment by oddhack** [comment]
@pdaniell-nv this looks OK. As it's a vendor extension we should just accept.

**Comment by jackohound** [comment]
From Qualcomm's view, this extension is ready to merge.    I thought GL had a practice of announcing and accepting vendor extensions in a WG call prior to merge.

**Comment by pdaniell-nv** [comment]
@oddhack approved to merge.

**Review by Perksey — APPROVED** [review]
Looks good on the grouping side of things!

**Comment by jackohound** [comment]
@oddhack, a reminder that we'd like to get this extension published as soon as you are able.

**Pull request merged**
