### PR TITLE
Create missing groups and group annotations

### PR DESCRIPTION
**Pull request by frabert**
This pull request aims to replace PR #45 which had unwanted side-effects. This time the only additions are new groups and new values to existing groups. Where possibile, I have kept the existing group names when they had proprietary suffixes (i.e. `BufferAccessARB`) even if used in non-extension methods (`glMapBuffer`).

I will wait for the mantainers' consent before squashing the commits

### CODE REVIEW

**Comment by oddhack** [comment]
This is still modifying parameter names for the BlendFuncSeparate* and Tex*StorageSparse* commands - please back those changes out as well. Otherwise it seems OK. It may be simplest to check by generating all the headers and verify that the only differences from upstream are the file-generated dates (then backing the generated files out of the branch before committing, as they tend to cause merge conflicts).

**Comment by frabert** [comment]
@oddhack This should have fixed it.

**Comment by luca-piccioni** [comment]
I found few wrong/incomplete groups at the moment. I'll link my gl.xml file based on this pull request for reference when I'll complete the review of the changes reflected on my projects.

**Comment by oddhack** [comment]
OK. I'm on post-meeting vacation now and won't be back for another week or so.

**Comment by frabert** [comment]
@luca-piccioni Can I merge your edits in this PR?

**Comment by luca-piccioni** [comment]
Sure!

Il sab 6 mag 2017, 15:29 Francesco Bertolaccini <notifications@github.com>
ha scritto:

**Comment by frabert** [comment]
@oddhack This is ready to be squashed and merged as soon as I receive approval

**Comment by frabert** [comment]
@oddhack Little up on this one. I merged the conflicting branches: should I squash now?

**Comment by pdaniell-nv** [comment]
Looks like there's a conflict that needs to be resolved.

**Comment by frabert** [comment]
@pdaniell-nv Should be fixed

**Comment by oddhack** [comment]
Replaced with #101

**Pull request closed without merging**
