### PR TITLE
Fix EXT_texture_compression_s3tc dependency in EXT_texture_sRGB_decode

### PR DESCRIPTION
**Pull request by pdaniell-nv**
This fixes issue #341

### CODE REVIEW

**Comment by hanfling** [comment]
This looks fine to me as far as S3TC is concerned, but I think Section 3.8.15 also misses listing the ETC2/ASTC texture formats, but thats certainly scope of another ticket/pull request.

**Comment by oddhack** [comment]
LGTM. Mark Approved when ready to merge.

**Comment by pdaniell-nv** [comment]
We discussed this PR in the OpenGL/ES meeting today and we're not sure if this change is even needed. I'll follow up in the #341 issue.

**Comment by pdaniell-nv** [comment]
I think this change is not needed as the extension already has a dependency on GL_EXT_texture_srgb, or OpenGL 2.1, where GL_EXT_texture_srgb was incorporated in the core.

**Pull request closed without merging**
