### PR TITLE
Nvx gpu multicast2

### PR DESCRIPTION
**Pull request by rbiermann**
Adding new NVIDIA extensions

GL_NVX_gpu_multicast2
GL_NVX_progress_fence
WGL_NV_multigpu_context

Please review and merge!

Kind regards,
Ralf Biermann (NVIDIA)

### CODE REVIEW

**Comment by dgkoch** [comment]
You probably want to remove xml/reg.pyc from the changeset.

**Comment by oddhack** [comment]
The extension numbers are going to need to be revised to account for a prior MR that overlapped. @rbiermann do you want this to do this? If the MR is otherwise ready to go, let me know and I'll take care of it.

**Comment by rbiermann** [comment]
> You probably want to remove xml/reg.pyc from the changeset.

Fine with that... I'm new to this github process so I added all file that were shown as modified in github desktop app.

**Comment by rbiermann** [comment]
> The extension numbers are going to need to be revised to account for a prior MR that overlapped. @rbiermann do you want this to do this? If the MR is otherwise ready to go, let me know and I'll take care of it.

I don't see the conflicting MR. If you could adjust the ext number during merge, I'd appreciate that!
I assume this is just moving one ext number in two files, right?

Thanks,
Ralf

**Comment by oddhack** [comment]
@dgkoch @pdaniell-nv I'm replacing this with #288, which fixes the conflicts and is a branch in this repo, so you can pull / push it to add the new KHR extension. As noted in #288, this PR didn't add the new interfaces to gl.xml / wgl.xml, so the headers won't contain them - it looks like this PR directly added the autogened files.

**Pull request closed without merging**
