### PR TITLE
Create missing enumerations

### PR DESCRIPTION
**Pull request by frabert**
This pull request fills several missing enumerations

### CODE REVIEW

**Comment by frabert** [comment]
I am planning to add more as I have just finished writing a tool to discover missing groups

**Comment by oddhack** [comment]
When you're done with this, please squash it down to a single commit. All looks fine so far.

**Comment by frabert** [comment]
@oddhack So I should close this PR when I'm done and re-open a new one containing a single commit?

**Comment by oddhack** [comment]
You can (if your git-fu is advanced enough) squash the commits in your local copy of the branch and force-push it to github, but your approach works too.

**Comment by frabert** [comment]
This is done. I will now try and squash the thing before it starts laying eggs.

**Comment by frabert** [comment]
@oddhack Done.

**Comment by oddhack** [comment]
Please see #46 / #47 and resubmit just the part of this changing the enum groups and adding group= tags to param tags. None of the group changes should have an effect on the generated headers.

**Comment by frabert** [comment]
@oddhack Ok, sorry for messing this up, I am trying to re-do this the right way now. Am I allowed to add group annotations for `GLenum` return types?

Like so:
````diff
         <command>
-            <proto><ptype>GLenum</ptype> <name>glClientWaitSync</name></proto>
+            <proto group="SyncStatus"><ptype>GLenum</ptype> <name>glClientWaitSync</name></proto>
             <param group="sync"><ptype>GLsync</ptype> <name>sync</name></param>
             <param><ptype>GLbitfield</ptype> <name>flags</name></param>
             <param><ptype>GLuint64</ptype> <name>timeout</name></param>
         </command>
````

**Comment by oddhack** [comment]
That's fine. It's the actual API - e.g. the resulting headers - that we don't want to change without more careful attention.

**Pull request merged**
