### PR TITLE
Binary-compatible fixes

### PR DESCRIPTION
**Pull request by stohrendorf**
* Add GL_COLOR_ATTACHMENT* members to DrawBufferMode
* Add GL_RGB32F to InternalFormat
* Add enum CopyImageSubDataTarget, using it for glCopyImageSubData instead of CopyBufferSubDataTarget
* Use DrawBufferMode instead of DrawBufferModeATI for glDrawBuffers
* Use GLenum instead of GLint for glTexImage2D internalformat parameter

### CODE REVIEW

**Comment by oddhack** [comment]
Mostly this looks OK to me - want to run it by the rest of the working group first -  but TexImage2D <internalformat> cannot be GLenum, because in the compatibility profile it accepts the integer values 1-4.

**Comment by oddhack** [comment]
Also I just accepted some other PRs which merged duplicate enum groups and caused some conflicts, so this will need to be rebased. I think if you just revert the TexImage2D change after rebasing, this will be uncontroversial.

**Comment by stohrendorf** [comment]
Rebased and reverted GLint/GLenum change.

**Comment by stohrendorf** [comment]
Also includes a few more fixes for enums referencing non-existing constants (missing underscores in names).

**Comment by oddhack** [comment]
@pdaniell-nv if you will sign off on this I'll merge it. The only questionable bit was reverted, so this is just modifying the enum groups and doesn't affect the headers at all.

**Comment by pdaniell-nv** [comment]
@oddhack approved to merge.

**Pull request merged**
