### PR TITLE
Enum fixes

### PR DESCRIPTION
**Pull request by tksuoran**

### CODE REVIEW

**Comment by oddhack** [comment]
This looks OK to me, although I suspect it may conflict with #273 once that's accepted. @pdaniell-nv are you OK with this?

**Comment by pdaniell-nv** [comment]
@oddhack if you are happy with this it's approved to merge.

**Comment by oddhack** [comment]
@tksuoran could you make sure  that this is doing the right thing now that #273 has been merged? The diff listing doesn't show conflicts, but it also doesn't seem to show the diffs against current head of master, and the #273 changes were fairly extensive, so I'm not confident it might not add changes in the wrong groups or something of that nature.

**Comment by Perksey** [comment]
@oddhack These enum groups were added in #273 and were also added here:
```
GetMultisamplePNameNV
ClampColorTargetARB
VertexAttribPointerPropertyARB
PointParameterNameARB
ClampColorTargetARB
ClampColorModeARB
BufferPNameARB
VertexAttribPropertyARB
```

**Comment by Perksey** [comment]
This PR looks stale. Maintainers have permission to edit PRs, so if you remove the aforementioned duplicate groupings this should be good to go.

**Comment by oddhack** [comment]
@Perksey @tksuoran I attempted to merge the duplicate groups and added a bunch of missing GL_ prefixes in bbd72c6 .

**Comment by Perksey** [comment]
Great, thank!

**Pull request merged**
