### PR TITLE
new NV memory usage query extension

### PR DESCRIPTION
**Pull request by klefebvre**
New Nvidia video memory usage query extension at the object level.

### CODE REVIEW

**Comment by oddhack** [comment]
reg.pyc shouldn't be getting checked in. That's a cache file generated by Python.

**Comment by klefebvre** [comment]
I'll remove it.

**Comment by klefebvre** [comment]
Sorry, I missed that file. I’ll remove it.

kevin

**Comment by klefebvre** [comment]
While I'm at it, should diag.txt be included (it appears to be a new file)?

**Comment by klefebvre** [comment]
starting over...

**Comment by oddhack** [comment]
diag.txt shouldn't be included. It's just a log file generated by the scripts. I apparently need to push a .gitignore including more stuff.

**Pull request closed without merging**
