### PR TITLE
fix some group definitions in gl.xml

### PR DESCRIPTION
**Pull request by 3b**
add some missing enums
fix references to enums that don't exist
merge some groups

### CODE REVIEW

**Comment by Perksey** [comment]
Duplicate of #328

**Comment by pdaniell-nv** [comment]
> Duplicate of #328

Looks like there is not 100% overlap with #328. Perhaps rebase this PR once #328 has been merged.

**Comment by Perksey** [comment]
Can you pull in the latest changes on master so we can review what this PR brings to the table ^_^

**Comment by pdaniell-nv** [comment]
@3b do you want to update your PR and resolve the conflicts?

**Comment by 3b** [comment]
OK, rebased onto master

**Comment by oddhack** [comment]
@pdaniell-nv seems benign to me, recommend accept.

**Comment by pdaniell-nv** [comment]
> ```
> Checking document...
> [25071, 20] GL02: Command  references invalid group ProgramTargetARB.
> [25135, 20] GL02: Command  references invalid group ProgramTargetARB.
> 
> 2 errors.
> ```

Approved to merge once the above is fixed.

**Comment by pdaniell-nv** [comment]
@oddhack, this is approved to merge.

**Pull request merged**
