### PR TITLE
Fixing some typos in EXT_external_objects

### PR DESCRIPTION
**Pull request by avoroshilov**
Just a couple of fixes to simple typos in `EXT_external_objects`

### CODE REVIEW

**Review by pdaniell-nv — APPROVED** [review]

**Comment by oddhack** [comment]
@pdaniell-nv I went ahead and merged this without the Approved milestone - sorry. But the changes are all trivially verifiable within the extension itself.

**Comment by Perksey** [comment]
> pdaniell-nv approved these changes 17 hours ago

Can/should this supersede the milestone?

**Comment by pdaniell-nv** [comment]
> > pdaniell-nv approved these changes 17 hours ago
> 
> Can/should this supersede the milestone? (given it's built-in GitHub functionality)

This approval was just from my wearing my individual contributor hat. When I set the Milestone to "Approved" it means it was approved by the OpenGL/ES working group.

There are times when @oddhack can just merge stuff when it is clearly editorial, so in this case what he did was fine.

**Comment by Perksey** [comment]
> When I set the Milestone to "Approved" it means it was approved by the OpenGL/ES working group.

Aaahhhh, thanks for the clarification! Didn't know that.

**Pull request merged**
